service: starwars
app: starwars
org: edwinsono

frameworkVersion: '2'
configValidationMode: off


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  role: arn:aws:iam::435545862549:role/starwars-dev
  stage: dev
  region: us-east-1

functions:
  listVehicles:
    handler: src/vehicles.list
    memorySize: 128
    description: vehicles starwars list.
    events:
      - http:
          path: vehicles
          method: get
          cors: true
  saveVehicle:
    handler: src/vehicles.save
    memorySize: 128
    description: vehicles starwars save.
    events:
      - http:
          path: vehicles
          method: post
          cors: true
plugins:
  - serverless-offline
